export interface DailyPortEvent {
  id: string;
  crrNumber: string;
  dateTime: string;
  attachments: (File | string)[];
  type: string;
  subType: string;
  location: string;
  description: string;
  responsibleDepartment: string;
  actionTaken: string;
  responseDate: string;
  notes: string;
}

export const EVENT_TYPES = [
  "Maintenance request",
  "HSE Related issues",
  "Fire Alarm/Indications",
  "Traffic violations",
  "Complaints",
  "Unsecured offices",
  "Smoking Violation",
  "Violation of Permit to work(PTW)",
  "Property Damages",
  "Illegal activity",
  "Property removals",
  "Death Cases",
  "Breach of Emaar Community Rules",
  "Parking related issues",
  "Key management",
  "Lost & Found",
  "Unauthorized access",
  "Water Leakage",
  "Fire",
  "Noises",
  "Elevator Entrapment",
  "Strike",
  "Fighting",
  "Drone Usage",
  "Medical Assistance",
  "Patient Shifting",
  "Media Shooting",
  "VIP Arrival",
  "Celebrity Arrival",
  "Inspection Related",
  "Lost Kids/Persons",
  "Authority Arrival",
  "Suspicious items",
  "Suspicious person",
  "Arguments",
  "Suicide Attempt",
  "Fatality",
  "CCTV Related",
  "Alcohol Related",
  "Gas leak",
  "Broken Down / Other Vehicle issues",
  "Family / Other Dispute",
  "Traffic Related Issues",
  "Trespass",
  "Power Failure",
  "New Opening/Modification",
  "Smoke",
  "Theft",
  "Unleashed Dogs",
  "Spill/Emissions",
  "Vehicle accidents",
  "Long parking vehicles",
  "Help",
  "Events related"
] as const;

export const SUB_TYPES = [
  "Internal & External Lighting",
  "Gate Block",
  "Unsafe riding violation",
  "Misuse of Public areas",
  "Landscape violation",
  "Speeding&Racing violation",
  "Pets Violations",
  "Driving Violations",
  "Elevator Malfunction",
  "Electricity Drop",
  "Drop Waste Sand",
  "Garbage",
  "Construction",
  "Agriculture",
  "Oil Stains",
  "High Speed",
  "Noise",
  "Underage Driven",
  "Drive Wrong Way",
  "Open Windows, Doors, Terrace & Shish Mat",
  "Drugs",
  "Internal & External Modifications",
  "Workers night sleep",
  "Night Works",
  "Materials Entry",
  "Planting basin",
  "Emaar Assets",
  "Owner Assets",
  "CCTV damage",
  "Owners",
  "Employees",
  "Animals",
  "Verbal or Physical Assault Against Individuals or Staff and Officials",
  "Fireworks",
  "Drinking Alcohol in Public Areas",
  "Unpermitted Fishing",
  "Misuse of Balconies and Corridors - Pet's Litter- Landscape",
  "Selling QR codes",
  "Unauthorized access",
  "Unpermitted Photoshoots, Advertising, Shows in Public areas",
  "Parking in non-designated areas",
  "Charge from non-designated areas",
  "Watch",
  "Sun Glasses",
  "Gold",
  "Phones",
  "Money",
  "Wallet",
  "Balls",
  "Bags",
  "Keys",
  "Charger",
  "AirPods",
  "Speakers",
  "Broken Pipes",
  "Broken Valve",
  "Broken Irrigation Sprinklers",
  "Broken taps",
  "Units",
  "Stores",
  "Offices",
  "others"
] as const;

export const LOCATIONS = [
  "Main Gates",
  "Ring Road",
  "7mart &Sports",
  "Security Building",
  "Road To Center",
  "Road To Gate0",
  "Road To Gate4",
  "Road To Safi",
  "Ring Road",
  "Gate 1",
  "Gate 2",
  "Gate 3",
  "Gate 4",
  "Gate0",
  "Arezzo",
  "Verona",
  "ISOLA",
  "VENETO",
  "Salerno",
  "Blanca",
  "VICTORIA",
  "Verdi",
  "Catania",
  "Catania Elevators",
  "Greek",
  "Valencia",
  "Marassi Bay",
  "Celia",
  "Safi",
  "Marina Buildings",
  "Marina Streets",
  "MARINA Promenade",
  "Riva",
  "Skaia",
  "Faya",
  "Lea",
  "Sales Center",
  "B.C.H in door",
  "B.C.H outdoor",
  "North Beach",
  "Safi Beach",
  "Community Cameras",
  "Catania Pools",
  "Mosque",
  "Parking Gate1 Right",
  "Park Mosque",
  "The Alley Mall Parking",
  "Parking Gate 1",
  "Parking water Park",
  "Parking (VIP)",
  "GOLF",
  "Blanca Hub",
  "HUBS-IT Data center",
  "Marassi -fence",
  "fence - Coast Road",
  "Yacht Club",
  "Sol",
  "The Hub",
  "Dropp off",
  "Blanca HK",
  "Verdi HK",
  "Catania HK",
  "M-Porium Mall",
  "H7",
  "Water Park",
  "Marina 2 Hub",
  "Marina 1 Hub",
  "Altea",
  "Verdi Hub",
  "other"
] as const;

export const DEPARTMENTS = [
  "FM IT",
  "development",
  "Hospitality FM",
  "CM FM",
  "CM",
  "FM",
  "Construction",
  "Construction FM",
  "Construction CM FM",
  "CM FM",
  "Operation",
  "Operation FM",
  "Hospitality",
  "Markting",
  "WareHouse",
  "Security"
];

export const ACTIONS_TAKEN = [
  "Report sent by mail",
  "Report sent by SalesForce",
  "Report sent by mail - Report sent by SalesForce"
];
